name: flutterplasma
description: Flutter app demonstrating some examples of graphics rendering.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supercharged: ^2.1.1
  simple_animations: ^5.0.2
  url_strategy: ^0.2.0
  url_launcher: ^6.2.6
  web: ^0.5.1
  sa3_liquid: ^1.0.1
  sa4_migration_kit: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/music.mp3
  fonts:
    - family: Work Sans
      fonts:
        - asset: fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Italic.ttf
          style: italic
        - asset: fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: fonts/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
